/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package report5;

public class App {


    public static void main(String[] args) {
        /*String str = null;     // String型変数 str を宣言し、初期値として null を代入する。
        try {
            System.out.println(str.length());
        } catch (NullPointerException e) {
            System.out.println("NullPointerException!");
            System.out.println(e.getMessage());
        }*/
        String str = "百二十三";
        int value = Integer.parseInt(str);
        
    }
}


